[package]
name = "sample_webview"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
windows-webview = { workspace = true }
windows-core = { workspace = true }

[dependencies.windows-sys]
workspace = true
features = [
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]

[lints]
workspace = true
